version: '3.7'

services: 
  redis:
    image: redis:5.0.6
    ports: 
      - 6379:6379

  node:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    environment: 
      - REDIS_HOST=redis